% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Measures\_of\_incidence\_2},
  pdfauthor={Анастасия Горшкова},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Measures\_of\_incidence\_2}
\author{Анастасия Горшкова}
\date{2024-10-06}

\begin{document}
\maketitle

\subsection{Задание 1 было
следующим:}\label{ux437ux430ux434ux430ux43dux438ux435-1-ux431ux44bux43bux43e-ux441ux43bux435ux434ux443ux44eux449ux438ux43c}

Врачи решили исследовать, как индекс массы тела (ИМТ) ассоциирован с
риском развития диабета 2-го типа.

Файл diabetes.csv содержит данные о случайной выборке из 200 жителей
населённого пункта N.

Для каждого респондента известен ИМТ (высокий или нормальный) и статус
по диабету (наличие/отсутствие диабета 2-го типа).

Определите, как высокий ИМТ ассоциирован c развитием диабета 2-го типа,

укажите относительный риск (relative risk) и абсолютную разницу в рисках
(risk difference).

Как вы проинтерпретируете полученные результаты?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"/Users/anastasiagorskova/BioStat\_2024/Measures\_of\_incidence\_2/diabetes.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 200 Columns: 3
## -- Column specification --------------------------------------------------------
## Delimiter: ","
## chr (2): ИМТ, Диабет
## dbl (1): ID
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{|\textgreater{}} \FunctionTok{head}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 3
##      ID ИМТ        Диабет
##   <dbl> <chr>      <chr> 
## 1     1 Высокий    Есть  
## 2     2 Высокий    Нет   
## 3     3 Нормальный Нет   
## 4     4 Высокий    Нет   
## 5     5 Высокий    Нет   
## 6     6 Высокий    Нет
\end{verbatim}

\section{NA checking}\label{na-checking}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(data))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

Отлично! В датасете нет пропущенных значений

\section{Let´s look on the data}\label{lets-look-on-the-data}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{|\textgreater{}} \FunctionTok{glimpse}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 200
## Columns: 3
## $ ID     <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, ~
## $ ИМТ    <chr> "Высокий", "Высокий", "Нормальный", "Высокий", "Высокий", "Высо~
## $ Диабет <chr> "Есть", "Нет", "Нет", "Нет", "Нет", "Нет", "Есть", "Есть", "Ест~
\end{verbatim}

\section{Changing char variables to logical
classes}\label{changing-char-variables-to-logical-classes}

Здесь мы заменяем ``Высокий'' на 1 и ``Нормальный'' на 0 в столбце ИМТ,
а также ``Есть'' на 1 и ``Нет'' на 0 в столбце ``Диабет''

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data}\SpecialCharTok{$}\NormalTok{ИМТ }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(}\FunctionTok{ifelse}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{ИМТ }\SpecialCharTok{==} \StringTok{"Высокий"}\NormalTok{, }\DecValTok{1}\NormalTok{, }\FunctionTok{ifelse}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{ИМТ }\SpecialCharTok{==} \StringTok{"Нормальный"}\NormalTok{, }\DecValTok{0}\NormalTok{, data}\SpecialCharTok{$}\NormalTok{ИМТ)))}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{Диабет }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(}\FunctionTok{ifelse}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Диабет }\SpecialCharTok{==} \StringTok{"Есть"}\NormalTok{, }\DecValTok{1}\NormalTok{, }\FunctionTok{ifelse}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Диабет }\SpecialCharTok{==} \StringTok{"Нет"}\NormalTok{, }\DecValTok{0}\NormalTok{, data}\SpecialCharTok{$}\NormalTok{Диабет)))}

\NormalTok{data }\SpecialCharTok{|\textgreater{}} \FunctionTok{glimpse}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 200
## Columns: 3
## $ ID     <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, ~
## $ ИМТ    <fct> 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, ~
## $ Диабет <fct> 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, ~
\end{verbatim}

\section{Summary}\label{summary}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{|\textgreater{}} \FunctionTok{summary}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        ID         ИМТ     Диабет 
##  Min.   :  1.00   0: 87   0:110  
##  1st Qu.: 50.75   1:113   1: 90  
##  Median :100.50                  
##  Mean   :100.50                  
##  3rd Qu.:150.25                  
##  Max.   :200.00
\end{verbatim}

\section{Формулируем
гипотезу}\label{ux444ux43eux440ux43cux443ux43bux438ux440ux443ux435ux43c-ux433ux438ux43fux43eux442ux435ux437ux443}

Нашей задачей является проверка гипотезы о том, что повышенный ИМТ
связан с наличием диабета

Для этого мы будем считать относительный риск (relative risk) и
абсолютную разницу в рисках (risk difference)

\section{Даем
определения}\label{ux434ux430ux435ux43c-ux43eux43fux440ux435ux434ux435ux43bux435ux43dux438ux44f}

Относительный риск в медицинской статистике и эпидемиологии ---
отношение риска наступления определенного события у лиц, подвергшихся
воздействию фактора риска, по отношению к контрольной группе.

То есть это когда мы делим один риск на другой.

Абсолютная разница в рисках - когда мы вычитаем одно значение из
другого.

\section{Сделаем таблицу сопряженности для дихотомических
переменнных}\label{ux441ux434ux435ux43bux430ux435ux43c-ux442ux430ux431ux43bux438ux446ux443-ux441ux43eux43fux440ux44fux436ux435ux43dux43dux43eux441ux442ux438-ux434ux43bux44f-ux434ux438ux445ux43eux442ux43eux43cux438ux447ux435ux441ux43aux438ux445-ux43fux435ux440ux435ux43cux435ux43dux43dux43dux44bux445}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Создание таблицы сопряженности для столбцов ИМТ и диабет}
\NormalTok{tabl }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{ИМТ, data}\SpecialCharTok{$}\NormalTok{Диабет)}

\CommentTok{\# Вывод таблицы}
\FunctionTok{print}\NormalTok{(tabl)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    
##      0  1
##   0 64 23
##   1 46 67
\end{verbatim}

Получается,

64 человека имеют нормальный вес и не имеют диабета,

23 человека имеют нормальный вес и диабет,

46 человека имеют избыточный вес и не имеют диабета,

67 человек имеют избыточный вес и диабет

\section{Считаем
риски}\label{ux441ux447ux438ux442ux430ux435ux43c-ux440ux438ux441ux43aux438}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Подсчет риска диабета для группы с высоким ИМТ}
\NormalTok{risk\_1 }\OtherTok{\textless{}{-}}\NormalTok{ tabl[}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(tabl[}\DecValTok{2}\NormalTok{, ])}

\CommentTok{\# Подсчет риска диабета для группы с низким ИМТ}
\NormalTok{risk\_0 }\OtherTok{\textless{}{-}}\NormalTok{ tabl[}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(tabl[}\DecValTok{1}\NormalTok{, ])}

\CommentTok{\# Подсчет относительного риска (RR)}
\NormalTok{relative\_risk }\OtherTok{\textless{}{-}}\NormalTok{ risk\_1 }\SpecialCharTok{/}\NormalTok{ risk\_0}

\CommentTok{\# Подсчет абсолютной разницы в рисках (RD)}
\NormalTok{risk\_difference }\OtherTok{\textless{}{-}}\NormalTok{ risk\_1 }\SpecialCharTok{{-}}\NormalTok{ risk\_0}

\CommentTok{\# Вывод результатов}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Относительный риск (RR):"}\NormalTok{, relative\_risk, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Относительный риск (RR): 2.242786
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Абсолютная разница в рисках (RD):"}\NormalTok{, risk\_difference, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Абсолютная разница в рисках (RD): 0.3285525
\end{verbatim}

Риск диабета для группы с высоким ИМТ: 0.5929204 Риск диабета для группы
с низким ИМТ: 0.2643678

Ответ: Относительный риск (RR): 2.24 Абсолютная разница в рисках (RD):
0.33

\section{Посчитаем хи квадрат на всякий
случай}\label{ux43fux43eux441ux447ux438ux442ux430ux435ux43c-ux445ux438-ux43aux432ux430ux434ux440ux430ux442-ux43dux430-ux432ux441ux44fux43aux438ux439-ux441ux43bux443ux447ux430ux439}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{chisq.test}\NormalTok{(tabl)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's Chi-squared test with Yates' continuity correction
## 
## data:  tabl
## X-squared = 20.132, df = 1, p-value = 7.228e-06
\end{verbatim}

Результат: X-squared = 20.132, df = 1, p-value = 7.228e-06

Получается, есть статистически значимая связь между высоким ИМТ и
диабетом

Причем у лиц с высоким ИМТ диабет встречается в более чем два раза чаще,
чем у лиц с низким ИМТ

Тут вроде все без подводных камней, так и ожидалось\ldots{}

\subsection{Задание 2 было
следующим:}\label{ux437ux430ux434ux430ux43dux438ux435-2-ux431ux44bux43bux43e-ux441ux43bux435ux434ux443ux44eux449ux438ux43c}

В городе N зафиксирована вспышка пневмонии.

Пострадало 250 человек, проживающих в разных домах.

Все они на протяжении последних двух недель посещали различные места:

торговые центры, рестораны и общественные мероприятия.

Для контроля взяли 750 человек, которые не заболели пневмонией.

Был проведен опрос о том, какие места каждый человек посещал
(pneumonia.csv).

Используя подходящую меру ассоциации, определите, какое место посещения
с наибольшей вероятностью связано с возникновением пневмонии.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"pneumonia.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 1000 Columns: 5
## -- Column specification --------------------------------------------------------
## Delimiter: ","
## chr (4): Группа, Торговый центр, Ресторан, Общественные мероприятия
## dbl (1): ID
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{|\textgreater{}} \FunctionTok{head}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 5
##      ID Группа    `Торговый центр` Ресторан `Общественные мероприятия`
##   <dbl> <chr>     <chr>            <chr>    <chr>                     
## 1     1 Пневмония Да               Да       Да                        
## 2     2 Пневмония Да               Да       Нет                       
## 3     3 Пневмония Нет              Да       Да                        
## 4     4 Пневмония Да               Да       Да                        
## 5     5 Пневмония Да               Нет      Нет                       
## 6     6 Пневмония Да               Да       Да
\end{verbatim}

\section{NA checking}\label{na-checking-1}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(data))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\section{Let´s look on the data}\label{lets-look-on-the-data-1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{|\textgreater{}} \FunctionTok{glimpse}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 1,000
## Columns: 5
## $ ID                         <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, ~
## $ Группа                     <chr> "Пневмония", "Пневмония", "Пневмония", "Пне~
## $ `Торговый центр`           <chr> "Да", "Да", "Нет", "Да", "Да", "Да", "Да", ~
## $ Ресторан                   <chr> "Да", "Да", "Да", "Да", "Нет", "Да", "Да", ~
## $ `Общественные мероприятия` <chr> "Да", "Нет", "Да", "Да", "Нет", "Да", "Нет"~
\end{verbatim}

\section{Changing char variables to logical
classes}\label{changing-char-variables-to-logical-classes-1}

Здесь мы заменяем Да на 1 и Нет на 0 и все переменные на факториальные

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data}\SpecialCharTok{$}\StringTok{\textasciigrave{}}\AttributeTok{Торговый центр}\StringTok{\textasciigrave{}} \OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(}\FunctionTok{ifelse}\NormalTok{(data}\SpecialCharTok{$}\StringTok{\textasciigrave{}}\AttributeTok{Торговый центр}\StringTok{\textasciigrave{}} \SpecialCharTok{==} \StringTok{"Да"}\NormalTok{, }\DecValTok{1}\NormalTok{, }\FunctionTok{ifelse}\NormalTok{(data}\SpecialCharTok{$}\StringTok{\textasciigrave{}}\AttributeTok{Торговый центр}\StringTok{\textasciigrave{}} \SpecialCharTok{==} \StringTok{"Нет"}\NormalTok{, }\DecValTok{0}\NormalTok{, data}\SpecialCharTok{$}\StringTok{\textasciigrave{}}\AttributeTok{Торговый центр}\StringTok{\textasciigrave{}}\NormalTok{)))}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{Ресторан }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(}\FunctionTok{ifelse}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Ресторан }\SpecialCharTok{==} \StringTok{"Да"}\NormalTok{, }\DecValTok{1}\NormalTok{, }\FunctionTok{ifelse}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Ресторан }\SpecialCharTok{==} \StringTok{"Нет"}\NormalTok{, }\DecValTok{0}\NormalTok{, data}\SpecialCharTok{$}\NormalTok{Ресторан)))}
\NormalTok{data}\SpecialCharTok{$}\StringTok{\textasciigrave{}}\AttributeTok{Общественные мероприятия}\StringTok{\textasciigrave{}} \OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(}\FunctionTok{ifelse}\NormalTok{(data}\SpecialCharTok{$}\StringTok{\textasciigrave{}}\AttributeTok{Общественные мероприятия}\StringTok{\textasciigrave{}} \SpecialCharTok{==} \StringTok{"Да"}\NormalTok{, }\DecValTok{1}\NormalTok{, }\FunctionTok{ifelse}\NormalTok{(data}\SpecialCharTok{$}\StringTok{\textasciigrave{}}\AttributeTok{Общественные мероприятия}\StringTok{\textasciigrave{}} \SpecialCharTok{==} \StringTok{"Нет"}\NormalTok{, }\DecValTok{0}\NormalTok{, data}\SpecialCharTok{$}\StringTok{\textasciigrave{}}\AttributeTok{Общественные мероприятия}\StringTok{\textasciigrave{}}\NormalTok{)))}

\NormalTok{data}\SpecialCharTok{$}\NormalTok{Группа }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Группа)}
                               
\NormalTok{data }\SpecialCharTok{|\textgreater{}} \FunctionTok{glimpse}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 1,000
## Columns: 5
## $ ID                         <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, ~
## $ Группа                     <fct> Пневмония, Пневмония, Пневмония, Пневмония,~
## $ `Торговый центр`           <fct> 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1~
## $ Ресторан                   <fct> 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1~
## $ `Общественные мероприятия` <fct> 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1~
\end{verbatim}

\section{Summary}\label{summary-1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{|\textgreater{}} \FunctionTok{summary}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        ID               Группа    Торговый центр Ресторан
##  Min.   :   1.0   Контроль :750   0:514          0:519   
##  1st Qu.: 250.8   Пневмония:250   1:486          1:481   
##  Median : 500.5                                          
##  Mean   : 500.5                                          
##  3rd Qu.: 750.2                                          
##  Max.   :1000.0                                          
##  Общественные мероприятия
##  0:493                   
##  1:507                   
##                          
##                          
##                          
## 
\end{verbatim}

Мы видим, что примерно по половине человек из нашего датасета побывали в
каждом из исследуемых мест.

В задаче структура данных напоминает дизайн исследования типа
``случай-контроль''. В этом подходе мы анализируем две группы: Пневмония
и Контроль. В исследованиях типа случай-контроль отношение шансов (OR)
является предпочтительной мерой ассоциации, потому что мы сравниваем
шансы какого-то воздействия или фактора (например, посещения места)
между группами (Пневмония и Контроль). OR позволяет оценить, как сильно
этот фактор ассоциирован с заболеванием (пневмонией) по сравнению с
контролем.

OR \textgreater{} 1: Посещение места увеличивает шансы заболеть
пневмонией по сравнению с контрольной группой.

OR \textless{} 1: Посещение места снижает шансы заболеть пневмонией.

OR = 1: Посещение места не связано с изменением вероятности заболеть
пневмонией.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Создание таблицы сопряженности для Торгового центра}
\NormalTok{table\_TC }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Группа, data}\SpecialCharTok{$}\StringTok{\textasciigrave{}}\AttributeTok{Торговый центр}\StringTok{\textasciigrave{}}\NormalTok{)}
\NormalTok{A\_TC }\OtherTok{\textless{}{-}}\NormalTok{ table\_TC[}\StringTok{"Пневмония"}\NormalTok{, }\StringTok{"1"}\NormalTok{]}
\NormalTok{B\_TC }\OtherTok{\textless{}{-}}\NormalTok{ table\_TC[}\StringTok{"Контроль"}\NormalTok{, }\StringTok{"1"}\NormalTok{]}
\NormalTok{C\_TC }\OtherTok{\textless{}{-}}\NormalTok{ table\_TC[}\StringTok{"Пневмония"}\NormalTok{, }\StringTok{"0"}\NormalTok{]}
\NormalTok{D\_TC }\OtherTok{\textless{}{-}}\NormalTok{ table\_TC[}\StringTok{"Контроль"}\NormalTok{, }\StringTok{"0"}\NormalTok{]}

\CommentTok{\# Расчет OR для Торгового центра}
\NormalTok{or\_TC }\OtherTok{\textless{}{-}}\NormalTok{ (A\_TC }\SpecialCharTok{*}\NormalTok{ D\_TC) }\SpecialCharTok{/}\NormalTok{ (B\_TC }\SpecialCharTok{*}\NormalTok{ C\_TC)}

\CommentTok{\# Создание таблицы сопряженности для Ресторана}
\NormalTok{table\_Restoran }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Группа, data}\SpecialCharTok{$}\NormalTok{Ресторан)}
\NormalTok{A\_Restoran }\OtherTok{\textless{}{-}}\NormalTok{ table\_Restoran[}\StringTok{"Пневмония"}\NormalTok{, }\StringTok{"1"}\NormalTok{]}
\NormalTok{B\_Restoran }\OtherTok{\textless{}{-}}\NormalTok{ table\_Restoran[}\StringTok{"Контроль"}\NormalTok{, }\StringTok{"1"}\NormalTok{]}
\NormalTok{C\_Restoran }\OtherTok{\textless{}{-}}\NormalTok{ table\_Restoran[}\StringTok{"Пневмония"}\NormalTok{, }\StringTok{"0"}\NormalTok{]}
\NormalTok{D\_Restoran }\OtherTok{\textless{}{-}}\NormalTok{ table\_Restoran[}\StringTok{"Контроль"}\NormalTok{, }\StringTok{"0"}\NormalTok{]}

\CommentTok{\# Расчет OR для Ресторана}
\NormalTok{or\_Restoran }\OtherTok{\textless{}{-}}\NormalTok{ (A\_Restoran }\SpecialCharTok{*}\NormalTok{ D\_Restoran) }\SpecialCharTok{/}\NormalTok{ (B\_Restoran }\SpecialCharTok{*}\NormalTok{ C\_Restoran)}

\CommentTok{\# Создание таблицы сопряженности для Общественных мероприятий}
\NormalTok{table\_Meropriyatiya }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Группа, data}\SpecialCharTok{$}\StringTok{\textasciigrave{}}\AttributeTok{Общественные мероприятия}\StringTok{\textasciigrave{}}\NormalTok{)}
\NormalTok{A\_Meropriyatiya }\OtherTok{\textless{}{-}}\NormalTok{ table\_Meropriyatiya[}\StringTok{"Пневмония"}\NormalTok{, }\StringTok{"1"}\NormalTok{]}
\NormalTok{B\_Meropriyatiya }\OtherTok{\textless{}{-}}\NormalTok{ table\_Meropriyatiya[}\StringTok{"Контроль"}\NormalTok{, }\StringTok{"1"}\NormalTok{]}
\NormalTok{C\_Meropriyatiya }\OtherTok{\textless{}{-}}\NormalTok{ table\_Meropriyatiya[}\StringTok{"Пневмония"}\NormalTok{, }\StringTok{"0"}\NormalTok{]}
\NormalTok{D\_Meropriyatiya }\OtherTok{\textless{}{-}}\NormalTok{ table\_Meropriyatiya[}\StringTok{"Контроль"}\NormalTok{, }\StringTok{"0"}\NormalTok{]}

\CommentTok{\# Расчет OR для Общественных мероприятий}
\NormalTok{or\_Meropriyatiya }\OtherTok{\textless{}{-}}\NormalTok{ (A\_Meropriyatiya }\SpecialCharTok{*}\NormalTok{ D\_Meropriyatiya) }\SpecialCharTok{/}\NormalTok{ (B\_Meropriyatiya }\SpecialCharTok{*}\NormalTok{ C\_Meropriyatiya)}

\CommentTok{\# Вывод результатов}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Отношение шансов для посещения Торгового центра:"}\NormalTok{, or\_TC, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Отношение шансов для посещения Торгового центра: 1.551787
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Отношение шансов для посещения Ресторана:"}\NormalTok{, or\_Restoran, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Отношение шансов для посещения Ресторана: 1.106742
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Отношение шансов для посещения Общественных мероприятий:"}\NormalTok{, or\_Meropriyatiya, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Отношение шансов для посещения Общественных мероприятий: 0.984125
\end{verbatim}

OR для посещения Торгового центра: 1.551787

OR для посещения Ресторана: 1.106742

OR для посещения Общественных мероприятий: 0.984125

\section{Интерпретация}\label{ux438ux43dux442ux435ux440ux43fux440ux435ux442ux430ux446ux438ux44f}

Шанс заболеть для посетителей ТЦ в полтора раза выше чем для
непосещавших его. \textbf{Скорее всего, распространение болезни
происходило именно в ТЦ.}

\end{document}
